### ISSUE TITLE
[BUG] Loot table only declared once, throws an error "already declared" 

### ISSUE THREAD

**Issue by amawdiin** [WingedSeal/jmc#56] opened 2023-11-02 10:39 UTC
## Describe the bug
"whip" loot table was only declared once but an error of duplicate declaration appears. this error can also be fixed if you import with a full path all the way from C: to project folder's subfolder.

## To Reproduce
[Steps to reproduce the behavior]

1. Download .zip
2. Download beet, jmc-beet, and zip i attached in here
3. drag the folder out of the archive
4. open the root folder in terminal
5. run 'beet' command in terminal 

## Expected behavior
To run and compile smoothly without any error messages. 

## Desktop

- OS Windows 10 

## Additional context
i use latest unreleased JMC build from github, i compile all my code in beet environment, i use python 3.12 (but that bug first happened when i still was on 3.11). 
ZIP ARCHIVE [bug bug bug.zip](https://github.com/WingedSeal/jmc/files/13237762/bug.bug.bug.zip)

**Comment by Nico314159** [comment] 2023-11-02 15:59
Is this *specifically* a jmc-beet issue? Or can it be replicated without beet?

**Comment by amawdiin** [comment] 2023-11-05 06:37
thats the thing, i dont know. but it has somethign to do with the path since if i type the import path all the way from c drive it will work fine and if i write the import path relative to project's folder it will break

**Comment by Nico314159** [comment] 2023-11-20 08:30
Turns out, this bug is actually a duplicate of #41. 

The reason you are having this problem is because you did `import "data/amandin/jmc/backend/*";`. Changing it to `import "data/amandin/jmc/backend/ddd";` or `import "data/amandin/jmc/backend/jjj";` fixes the problem because then it means the loot table is only imported once and not twice.

**Comment by WingedSeal** [comment] 2023-11-20 09:28
Fixed in https://github.com/WingedSeal/jmc/commit/d0a147598979fbd108f8a062797e62febdb96baf

**Closed** 2023-11-20 09:28 UTC
Labels: Type: Bug, Status: Fixed, Priority: Medium
